
# Redirect all HTTP to HTTPS
server {
  listen 80;
  server_name srhs.art www.srhs.art;
  return 301 https://www.srhs.art$request_uri;
}

# Redirect HTTPS non-www to www
server {
  listen 443 ssl;
  server_name srhs.art;
  ssl_certificate /etc/letsencrypt/live/srhs.art/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/srhs.art/privkey.pem;
  return 301 https://www.srhs.art$request_uri;
}

# Main HTTPS server
server {
  listen 443 ssl;
  server_name www.srhs.art;
  ssl_certificate /etc/letsencrypt/live/www.srhs.art/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.srhs.art/privkey.pem;
  root /var/www/vhosts/srhs.art;
  access_log /var/www/log/srhs.art.access.log;
  error_log /var/www/log/srhs.art.error.log info;

  location / {
    try_files $uri $uri/ =404;
  }
}

